import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;

import java.util.HashMap;
import java.util.Map;

import static spark.Spark.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        staticFileLocation("/public");
        String layout = "templates/layout.vtl";

        ProcessBuilder process = new ProcessBuilder();
        Integer port;
        if (process.environment().get("PORT") != null) {
            port = Integer.parseInt(process.environment().get("PORT"));
        } else {
            port = 4567;
        }

        port(port);

        //get main page
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add animal form
        get("/addAnimal", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("sightings", Sightings.all());
            model.put("template", "templates/addAnimal.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get all animals
        get("/allAnimals", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("animals", Aminals.all());
            model.put("template", "templates/allAnimals.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add animal
        post("/addAnimal", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();

//            Integer i = Integer.parseInt(request.queryParams("sightingId"));
            Sightings sightings = Sightings.find(Integer.parseInt(request.queryParams("sightingId")));
            String name = request.queryParams("name");
            Aminals newAnimal = new Aminals(name, sightings.getId());
            newAnimal.save();
            model.put("sightings", sightings);
            String url = String.format("/allAnimals", newAnimal.getId());
            response.redirect(url);
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());


        //ADD SIGHTING

        //add sighting form
        get("/addSighting", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/addSighting.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add sighting
        post("/AddSighting", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            String name = request.queryParams("name");
            String location = request.queryParams("location");
            Sightings sightings = new Sightings(name, location);
            String url = String.format("/allSightings", sightings.getId());
            sightings.save();
            model.put("sightings", sightings);
            response.redirect(url);
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get all sightings
        get("/allSightings", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("sightings", Sightings.all());
            model.put("template", "templates/allSightings.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get sighting details page
        //add sighting form
        get("/sightingDetails/:id", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            Sightings sightings = Sightings.find(Integer.parseInt(request.params(":id")));
            model.put("sightings", sightings);
            model.put("template", "templates/sightingDetails.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());


    }
}
